<?php
/*
 * This file is part of the Sift PHP framework.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Plugins config handler
 *
 * @package    Sift
 * @subpackage config
 */
class sfPluginsConfigHandler extends sfDefineEnvironmentConfigHandler
{
    /**
     * Executes this configuration handler.
     *
     * @param array An array of absolute filesystem path to a configuration file
     *
     * @return string Data to be written to a cache file
     */
    public function execute($configFiles)
    {
        $config = self::mergeEnvironment(self::parseYamls($configFiles));

        $myConfig = array();
        foreach ((array)$config as $plugin => $options) {
            if (!is_array($options)) {
                $options = array();
            }

            if (isset($options['disabled'])) {
                if ($options['disabled']) {
                    continue;
                }
                unset($options['disabled']);
            }

            $myConfig[$plugin] = $options;
        }

        // compile data
        $retval = "<?php\n" .
            "// auto-generated by %s\n" .
            "// date: %s\nreturn %s;\n";
        $retval = sprintf($retval, __CLASS__, date('Y/m/d H:i:s'), $this->varExport($myConfig));

        return $retval;
    }

}
