<?php
/*
 * This file is part of the Sift PHP framework.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * sfTextMacrosConfigHandler parses macros configuration files from
 * text_macros.yml files
 *
 * @package    Sift
 * @subpackage config
 */
class sfTextMacrosConfigHandler extends sfSimpleYamlConfigHandler {

  /**
   * Parses configuration files
   *
   * @param array $configFiles
   * @return string
   */
  public function execute($configFiles)
  {
    $config = $this->parseYamls($configFiles);
    $data   = array();
    foreach($config as $tag => $callable)
    {
      if(!is_array($callable) && !is_callable($callable))
      {
        $callable = array($callable, 'getHtml');
      }
      $data[] = sprintf("sfTextMacroRegistry::add('%s', %s);\n", $tag, var_export($callable, true));
    }

    // compile data
    $retval = sprintf("<?php\n"
                      ."// auto-generated by sfTextMacrosConfigHandler\n"
                      ."// date: %s\n\n"
                      ."%s",
                      date('Y/m/d H:i:s'), join("\n",$data));
    return $retval;
  }

}