#!/usr/bin/env php
<?php
/*
 * This file is part of the Sift PHP framework.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
chdir(dirname(__FILE__));
include 'config/config.php';
include $sf_sift_data_dir . '/bin/sift.php';
