<?php
// auto-generated by sfValidatorConfigHandler
// date: 2013/01/15 14:51:21

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'sift/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['nameValidator'] = new sfStringValidator();
  $validators['nameValidator']->initialize($context, array (
  'min' => 10,
  'min_error' => 'nameValidator',
));
  $validatorManager->registerName('input1', 0, 'Required', null, 'group1', false);
  $validatorManager->registerName('input2', 0, 'Required', null, 'group1', false);
  $validatorManager->registerValidator('input2', $validators['nameValidator'], null);
  $validatorManager->registerName('input3', 0, 'Required', null, 'group2', false);
  $validatorManager->registerName('input4', 0, 'Required', null, 'group2', false);
  $context->getRequest()->setAttribute('fillin', array (
), 'sift/filter');
}
