<?php
// auto-generated by sfFilterConfigHandler
// date: 2013/01/15 14:51:21

list($class, $parameters) = (array) sfConfig::get('sf_rendering_filter', array('sfRenderingFilter', array (
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_i18n_filter', array('sfI18nFilter', array (
  'add_stylesheet' => false,
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

// does this action require security?
if ($actionInstance->isSecure())
{
  if (!in_array('sfSecurityUser', class_implements($this->context->getUser())))
  {
    $error = 'Security is enabled, but your sfUser implementation does not implement sfSecurityUser interface';
    throw new sfSecurityException($error);
  }
  
list($class, $parameters) = (array) sfConfig::get('sf_security_filter', array('sfBasicSecurityFilter', array (
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);
}

list($class, $parameters) = (array) sfConfig::get('sf_myFilter_filter', array('myFilter', null));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_common_filter', array('sfCommonFilter', array (
  'javascript_config' => false,
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_flash_filter', array('sfFlashFilter', array (
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_execution_filter', array('sfExecutionFilter', array (
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

