<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/01/15 14:51:20
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
