<?php
// auto-generated by myViewConfigHandler
// date: 2013/01/15 14:51:20
$context  = sfContext::getInstance();
$response = $context->getResponse();


  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'sift/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!$context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('layout'.$this->getExtension());
  }

  $response->addHttpMeta('content-type', 'text/html', false);
  $response->setTitle('symfony project', true, false, true);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'symfony project', false, false);
  $response->addMeta('keywords', 'symfony, project', false, false);
  $response->addMeta('language', 'en', false, false);


  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('ie8', '', array (  'ie_condition' => 'lte IE 10',));


